services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pet-app:latest
    container_name: pet-app-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
      - REDIS_DB=0
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - redis
    networks:
      - pet-app-network

  nginx:
    image: nginx:alpine
    container_name: pet-app-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pet-app-network

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    image: pet-app:vite
    container_name: pet-app-vite
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - VITE_APP_URL=http://localhost:5173
    ports:
      - "5173:5173"
    networks:
      - pet-app-network

  redis:
    image: redis:7-alpine
    container_name: pet-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pet-app-network

volumes:
  redis_data:

networks:
  pet-app-network:
    driver: bridge
